### PR TITLE
Update info to 2.1.28 and some syntax

### PR DESCRIPTION
**Pull request by guillem-palau-salva**
Some info was outdated, i.e. the changes were introduced before .28. Feel free to adapt the wording in the changes that are more narrative.

I hope at least I saved you some time.

Cheers

### CODE REVIEW

**Comment by guillem-palau-salva** [comment]
should the FAQ redirect to https://faqs.ankiweb.net? It is kind of empty.

**Comment by dae** [comment]
Hi Guillem,

A funding file seems to have slipped in, and I didn't want to delete it as it seems to be your master branch - would you mind resubmitting the changes using a separate branch?

I had meant to delete the rest of faqs when linking to the separate faqs repo - have done that now.

**Comment by guillem-palau-salva** [comment]
My apologies,

I though the funding was only added to the Spanish branch. I am still learning how this works.

**Comment by dae** [comment]
Thanks Guillem :-)

**Pull request merged**
