### PR TITLE
Add paragraph about search replacing

### PR DESCRIPTION
**Pull request by RumovZ**
Are the kbd tags fine? I would then update the rest of browsing.md accordingly as it makes it easier to distinguish key names and text input which are currently both styled as code.

### CODE REVIEW

**Comment by dae** [comment]
I think kbd is intended to look like an actual key, so the individual characters should be listed separately as in the demo on this page: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd

Docsify supports it, and I'd be happy to accept such a change if you'd like to make it.

**Comment by RumovZ** [comment]
Individual keys look way better, indeed. The tag nesting that they also suggest doesn't sound like a good idea, though, so I've decided to go with `<kbd>key1</kbd>+<kbd>key2</kbd>-click` and changed it for the whole manual.

**Comment by dae** [comment]
Thanks!

**Comment by RumovZ** [comment]
It turns out the kbd styling is terrible on Docsify. Can we add manual styling to fix this? 

grafik

**Comment by dae** [comment]
Should be possible to inject some css into index.html - you can test locally by installing docsify-cli with npm/yarn, then running 'docsify serve'

**Pull request merged**
