### PR TITLE
fixed typos: eg -> e.g.

### PR DESCRIPTION
**Pull request by MiVHQW**
eg to e.g.

### CODE REVIEW

**Comment by dae** [comment]
I'm fine with this change, but there are a number of other cases in the manual where 'eg' has been used. So we don't have to create+review a whole bunch of separate PRs, it would be great if you could address the other usages of 'eg' in this same PR. Also please note you can push updates to this PR; you don't need to delete and create a new one.

**Comment by MiVHQW** [comment]
I'd love to do that. I will update my PR with all the eg usages soon.

**Comment by MiVHQW** [comment]
I've looked for all occurrences of eg and changed them to e.g. now ;)

**Comment by dae** [comment]
Thanks Gabriel!

**Pull request merged**
